version: '3.3'

services:
    supertest:
        image: node:latest
        container_name: tests
        working_dir: /home
        volumes:
            - .:/home
        command: >
            sh -c "npm install && npm run test"